---
title: "Machine Learning Course Project"
author: "Luca Vignali"
date: "13 luglio 2015"
output: html_document
---

Outcome is the "classe" variable, predict with any of the other variables. 

## Model Creation

## Cross Validation

## Expected Out of Sample error

## Motivate your choices

## Precict the 20 cases of test set

1. Your submission should consist of a link to a Github repo with your R markdown and compiled HTML file describing your analysis. Please constrain the text of the writeup to < 2000 words and the number of figures to be less than 5. It will make it easier for the graders if you submit a repo with a gh-pages branch so the HTML page can be viewed online (and you always want to make it easy on graders :-).


## Evaluation Criteria
* Has the student submitted a github repo?
* Does the submission build a machine learning algorithm to predict activity quality from activity monitors?
* Do the authors describe what they expect the out of sample error to be and estimate the error appropriately with cross-validation?





When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{load_datasets}
training <- read.csv("pml-training-csv")
testing <- read.csv("pml-testing.csv")
```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
